# Generated by Django 3.0.6 on 2020-05-27 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False)),
                ('apellidos', models.CharField(max_length=25)),
                ('nombres', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ['id_autor'],
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['id_categoria'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=12)),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(blank=True, max_length=128, null=True)),
                ('correo_electronico', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['id_cliente'],
            },
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('isbn', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=128)),
                ('fecha_pub', models.DateField(blank=True, null=True)),
                ('precio', models.IntegerField()),
                ('portada', models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='portada/', verbose_name='Imagen de Portada')),
                ('autor', models.ManyToManyField(to='libreriaApp.Autores')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreriaApp.Categorias')),
            ],
            options={
                'ordering': ['isbn'],
            },
        ),
        migrations.CreateModel(
            name='PedidosCliente',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('nro_pedido', models.CharField(max_length=255, unique=True)),
                ('fecha_pedido', models.DateField(auto_now=True)),
                ('cantidad', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreriaApp.Cliente')),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreriaApp.Libros')),
            ],
            options={
                'ordering': ['nro_pedido'],
            },
        ),
    ]
