# Generated by Django 3.0.6 on 2020-05-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreriaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='portada',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='media/portada/', verbose_name='Imagen de Portada'),
        ),
    ]
