# Generated by Django 3.0.6 on 2020-06-01 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreriaApp', '0003_auto_20200526_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libros',
            old_name='autor',
            new_name='id_autor',
        ),
    ]
