# Generated by Django 3.0.6 on 2020-06-01 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreriaApp', '0004_auto_20200601_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='id_autor',
        ),
        migrations.AddField(
            model_name='libros',
            name='id_autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libreriaApp.Autores'),
            preserve_default=False,
        ),
    ]
