# Generated by Django 3.0.6 on 2020-06-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreriaApp', '0005_auto_20200601_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='id_autor',
        ),
        migrations.AddField(
            model_name='libros',
            name='id_autor',
            field=models.ManyToManyField(to='libreriaApp.Autores'),
        ),
    ]
