# Generated by Django 3.0.6 on 2020-05-05 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False)),
                ('apellidos', models.CharField(max_length=25)),
                ('nombres', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'autores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=12)),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(blank=True, max_length=128, null=True)),
                ('correo_electronico', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('isbn', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=128)),
                ('fecha_pub', models.DateField(blank=True, null=True)),
                ('precio', models.IntegerField()),
                ('portada', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'libros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PedidosCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_pedido', models.IntegerField()),
                ('fecha_pedido', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('valor', models.IntegerField()),
            ],
            options={
                'db_table': 'pedidos_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LibroPorAutor',
            fields=[
                ('id_autor', models.OneToOneField(db_column='id_autor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='libreriajjvaApp.Autores')),
            ],
            options={
                'db_table': 'libro_por_autor',
                'managed': False,
            },
        ),
    ]
