# Generated by Django 3.0.6 on 2020-05-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='perfil/avatar.png', max_length=200, upload_to='perfil/', verbose_name='Imagen de Perfil'),
        ),
    ]
